name: "Auto Release"
on:
  pull_request:
    types:
      - closed

jobs:
  auto-release:
    if: github.event.pull_request.merged == true && github.event.pull_request.user.login == 'merger-bot[bot]'
    name: "Auto Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: |
          VERSION=$(sed -n 's/^ARG VERSION="\([.0-9]*\)"/\1/p' Dockerfile)
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: "softprops/action-gh-release@v1"
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag_name: ${{ steps.get-version.outputs.version }}
          generate_release_notes: true
