name: "Auto Updated"

on:
  schedule:
    - cron: "50 23 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  check-new-release:
    name: "Check New Release"
    runs-on: "ubuntu-26.04"
    outputs:
      release: ${{ steps.new-release.outputs.release }}
      version: ${{ steps.new-release.outputs.version }}
    steps:
      - id: new-release
        run: |
          MEGABASTERD_APP_VERSION=$(curl -s https://api.github.com/repos/tonikelope/megabasterd/releases/latest | jq -r .tag_name | sed 's/^.\{1\}//g' | tr -d "[:space:]")
          MEGABASTERD_DOCKER_VERSION=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest | jq -r .tag_name | sed 's/^.\{1\}//g' | tr -d "[:space:]" || echo -n "0")
          if [ ! "${MEGABASTERD_APP_VERSION}" = "${MEGABASTERD_DOCKER_VERSION}" ]; then
            echo "release=TRUE" >> $GITHUB_OUTPUT
            echo "version=${MEGABASTERD_APP_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "release=FALSE" >> $GITHUB_OUTPUT
          fi

  Updated-Megabasterd:
    runs-on: ubuntu-26.04
    needs: check-new-release
    if: ${{ needs.check-new-release.outputs.release == 'TRUE' }}
    steps:
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Commit changes and create PR
        env:
          NEW_VERSION: ${{ needs.check-new-release.outputs.version }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git config --local user.email "131801252+merger-bot[bot]@users.noreply.github.com"
          git config --local user.name "merger-bot[bot]"
          git checkout -B auto-update
          sed -i "s/ENV MEGABASTERD_VERSION=\"[^\"]*\"/ENV MEGABASTERD_VERSION=\"${NEW_VERSION}\"/g" Dockerfile
          git commit -am "Updated MegaBasterd to: ${NEW_VERSION}"
          git push -u origin auto-update --force
          PR_URL=$(gh pr create -f -l "automated pr" -l "update")
          gh pr merge --squash --auto "$PR_URL"
