PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE downloads(url TEXT, email TEXT, path TEXT, filename TEXT, filekey TEXT, filesize UNSIGNED BIG INT, filepass VARCHAR(64), filenoexpire VARCHAR(64), custom_chunks_dir TEXT, PRIMARY KEY ('url'), UNIQUE(path, filename));
CREATE TABLE uploads(filename TEXT, email TEXT, url TEXT, ul_key TEXT, parent_node TEXT, root_node TEXT, share_key TEXT, folder_link TEXT, bytes_uploaded UNSIGNED BIG INT, meta_mac TEXT, PRIMARY KEY ('filename'), UNIQUE(filename, email));
CREATE TABLE settings(key VARCHAR(255), value TEXT, PRIMARY KEY('key'));
INSERT INTO settings VALUES('master_pass_salt','p2cPG3xumeP3DmWzaFxYoQ==');
INSERT INTO settings VALUES('verify_down_file','no');
INSERT INTO settings VALUES('upload_log','yes');
INSERT INTO settings VALUES('random_proxy','yes');
INSERT INTO settings VALUES('use_slots_down','yes');
INSERT INTO settings VALUES('limit_download_speed','no');
INSERT INTO settings VALUES('smartproxy_ban_time','300');
INSERT INTO settings VALUES('use_proxy','no');
INSERT INTO settings VALUES('language','EN');
INSERT INTO settings VALUES('run_command_path','');
INSERT INTO settings VALUES('custom_proxy_list','');
INSERT INTO settings VALUES('proxy_pass','');
INSERT INTO settings VALUES('default_slots_up','6');
INSERT INTO settings VALUES('default_down_dir','/output');
INSERT INTO settings VALUES('run_command','no');
INSERT INTO settings VALUES('dark_mode','no');
INSERT INTO settings VALUES('smartproxy_timeout','5');
INSERT INTO settings VALUES('default_slots_down','6');
INSERT INTO settings VALUES('proxy_host','');
INSERT INTO settings VALUES('reset_slot_proxy','yes');
INSERT INTO settings VALUES('max_downloads','4');
INSERT INTO settings VALUES('use_custom_chunks_dir','no');
INSERT INTO settings VALUES('custom_chunks_dir',NULL);
INSERT INTO settings VALUES('proxy_port','');
INSERT INTO settings VALUES('megacrypter_reverse','no');
INSERT INTO settings VALUES('start_frozen','no');
INSERT INTO settings VALUES('max_uploads','4');
INSERT INTO settings VALUES('debug_file','no');
INSERT INTO settings VALUES('megacrypter_reverse_port','9999');
INSERT INTO settings VALUES('max_upload_speed','5');
INSERT INTO settings VALUES('clipboardspy','yes');
INSERT INTO settings VALUES('use_mega_account_down','no');
INSERT INTO settings VALUES('proxy_user','');
INSERT INTO settings VALUES('max_download_speed','5');
INSERT INTO settings VALUES('force_smart_proxy','no');
INSERT INTO settings VALUES('limit_upload_speed','no');
INSERT INTO settings VALUES('mega_account_down',NULL);
INSERT INTO settings VALUES('smartproxy_autorefresh_time','60');
INSERT INTO settings VALUES('font_zoom','80');
INSERT INTO settings VALUES('thumbnails','yes');
INSERT INTO settings VALUES('smart_proxy','no');
INSERT INTO settings VALUES('upload_public_folder','no');
INSERT INTO settings VALUES('font','DEFAULT');
CREATE TABLE mega_accounts(email TEXT, password TEXT, password_aes TEXT, user_hash TEXT, PRIMARY KEY('email'));
CREATE TABLE elc_accounts(host TEXT, user TEXT, apikey TEXT, PRIMARY KEY('host'));
CREATE TABLE mega_sessions(email TEXT, ma BLOB, crypt INT, PRIMARY KEY('email'));
CREATE TABLE downloads_queue(url TEXT, PRIMARY KEY('url'));
CREATE TABLE uploads_queue(filename TEXT, PRIMARY KEY('filename'));
COMMIT;